### ISSUE TITLE
background-image not working correctly in css

### ISSUE THREAD

**Issue by alaarab** [ncuesta/dropzonejs-rails#12]
.dropzone .dz-default.dz-message {
background-image: "/assets/dropzone/spritemap-82e181cf9db0563178952adb97cbad6c.png";
}

is generated in my css/javascript. This is giving me an invalid property value, and anything that uses the spritemap does not show.

I can fix it in the inspector but don't know how to fix it so the images show by changing it to 

background-image: url("../dropzone/spritemap.png");

Does anyone know why this is happening?

**Comment by BlazPerus** [comment]
I still have problems with this one.. Doesn't work in production straight out of the box, but works localy.

**Comment by ncuesta** [comment]
Maybe it's missing from `Rails.application.config.assets.precompile`?

Are you using Rails? If so, which version?
