### ISSUE TITLE
Dropzone does not load when I redirect to my form page, but it does when I refresh my browser.

### ISSUE THREAD

**Issue by kranthi1027** [ncuesta/dropzonejs-rails#16]
Hi,
   I'm trying my hands on dropzone.js using a test app.  I have used carrierwave for the file uploads.I could make everything work. The only problem I face is when I redirect to my form page from my index page using "<%= link_to 'New Item', new_my_item_path %>", I dont see the dropzone functionality active. But if I refresh the page it shows. It works even if I directely set my browser url to http://localhost:3000/my_items/new. What is that I'm doing wrong here. I have been looking over internet for quite sometime but it looks like no one else faced the same problem.

**Comment by liyakun** [comment]
@ncuesta @kranthi1027 , I also have this issue and thank you very much for your solution.

**Comment by kranthi1027** [comment]
@liyakun  Glad it helped! From my experience I can say dropzone is really amazing.
