### ISSUE TITLE
Just updated to the latest version and things a messed up

### ISSUE THREAD

**Issue by THPubs** [ncuesta/dropzonejs-rails#18]
Just updated to the latest version of the gem and the styles are broken. In the previous version they worked fine.

[Screenshot](http://i.imgur.com/D0Sa9gd.png)
![Screenshot](http://i.imgur.com/D0Sa9gd.png)

**Comment by ncuesta** [comment]
@THPubs, @elsurudo do you still get the same with today's release?

**Comment by tangens** [comment]
I have the same problem with 0.5.3 and 0.6.0 versions.

**Comment by ncuesta** [comment]
@tangens can you please elaborate a bit more on your issue? Is it reproducible in your local environment , in production or in both?

**Comment by tangens** [comment]
@ncuesta in local and demo environment. (prod environment does not exist at moment). Now i putted css code from github to my local css files.

**Comment by ncuesta** [comment]
@tangens thanks for that info, are you requiring `dropzone` via sprockets in your `application.css`? Some folks had a similar issue and it got solved by adding it to their `application.css`

**Comment by tangens** [comment]
@ncuesta I use sass and in my application.scss i used before: @import "dropzone/dropzone";

**Comment by ncuesta** [comment]
I haven't tried including it that way, could you give it a try and use Sprockets to require it instead of `@import`ing it? Just to make sure that's not the root cause.

**Comment by THPubs** [comment]
Sorry for the late reply. The new release have fixed the issue. But many people might think that the new version is broken because the new version have a different style. At first it looks blank. I also thought it's broken. But after checking the dropzone website I realized that the it's the new way.
