### ISSUE TITLE
0.6.0 doesn't exist

### ISSUE THREAD

**Issue by Juuro** [ncuesta/dropzonejs-rails#25]
Sadly `gem 'dropzonejs-rails', '~> 0.6.0'` doesn't work. I get the follwoing error:

```
Could not find gem 'dropzonejs-rails (~> 0.6.0) ruby' in the gems available on this machine.
```
 Apparently there is noch 0.6.x? Did you mean `0.5.0`? This works for me:

```
gem 'dropzonejs-rails', '~> 0.5.0'
```

It loads 0.5.3.

**Comment by ncuesta** [comment]
Oops.. totally right! I missed that one.. I'm updating the README now. Thanks @Juuro
