### ISSUE TITLE
cannot trigger 'removedFile' event

### ISSUE THREAD

**Issue by anklos** [ncuesta/dropzonejs-rails#26]
in my js file, I have set up something like this:

```js
$(document).ready(function(){

  Dropzone.autoDiscover = false;

  var dropzone = new Dropzone (".dropzone", {
    maxFilesize: 256, // Set the maximum file size to 256 MB
    paramName: "document[attachment]", // Rails expects the file upload to be something like model[field_name]
    addRemoveLinks: true // Don't show remove links on dropzone itself.
  });

  dropzone.on("removedFile", function(file){
    alert('remove triggered');
  });

  dropzone.on("addedFile", function(file){
    alert('add triggered');
  });

  dropzone.on("success", function(file){
    alert('success triggered');
  });
});
```

I could get he success event, however I cannot get `removedFile` event when I delete the file from drop zone. Also it cannot trigger `addedFile` event even the file has been uploaded successfully to my server.

Is there anything I miss here? Thanks in advance.

**Comment by ncuesta** [comment]
Hi @anklos, it looks like an issue with Dropzone itself. You may want to head to [their repo](https://github.com/enyo/dropzone/issues) for this kind of problems.
