### ISSUE TITLE
Getting [object Object] error inside data-dz-errormessage

### ISSUE THREAD

**Issue by andiruleu** [ncuesta/dropzonejs-rails#28]
Losing my mind over this... I have no idea whats causing this. Please someone help! I'm able to drag image into the box, but what comes out is the error.

Here's my ticket in stackoverflow, no ones able to solve this. hopefully someone here can help.

http://stackoverflow.com/questions/31496171/ruby-on-rails-dropzone-js-and-paperclip-getting-object-object-but-why/31531948?noredirect=1#comment51065445_31531948

**Comment by ncuesta** [comment]
Hi, you may find more help if you post the issue to dropzone's repo. This is
just a wrapper around the js library to ease its inclusion in Rails projects.
Good luck!

Nahuel Cuesta Luengo
On mié, jul 22, 2015 at 2:55 a.m., ncuesta/dropzonejs-rails
<reply@reply.github.com>
wrote:
Losing my mind over this... I have no idea whats causing this. Please someone
help! I'm able to drag image into the box, but what comes out is the error.

Here's my ticket in stackoverflow, no ones able to solve this. hopefully someone
here can help.


http://stackoverflow.com/questions/31496171/ruby-on-rails-dropzone-js-and-paperclip-getting-object-object-but-why/31531948?noredirect=1#comment51065445_31531948
[http://stackoverflow.com/questions/31496171/ruby-on-rails-dropzone-js-and-paperclip-getting-object-object-but-why/31531948?noredirect=1#comment51065445_31531948]
