### ISSUE TITLE
additional form fields

### ISSUE THREAD

**Issue by syllogismus** [ncuesta/dropzonejs-rails#31]
hi,

im trying to get the plugin working. i can do drag & drop files but then i have a hardtime to assign the parameters to paperclip.
 <%= form_tag '/media_contents', method: :post, class: "dropzone form", id: "media-dropzone" do %>
          <div class="fallback">
            <%= file_field_tag "media", multiple: true%>
          </div>
        <% end %>

also, how can i add additional hiddenfields? when i add a hidden_tag outside of the fallback class, then it fallsback to simple upload button, inside of the div it doesnt even show up on the server side...nor in the html source. is there additional configuration needed?

tia

**Comment by ncuesta** [comment]
Hi @syllogismus, I think your questions may be better answered in the library's own repo. As far as I can see, you're having issues with the Dropzone JS library and not with this gem _per se_.

Anyway, I think that you're having a parameter naming issue. Have you checked which parameters are getting back to the server when the files are uploaded? You may want to check [this part of Dropzone's configuration](http://www.dropzonejs.com/#configuration), specially the `paramName` part :wink:

Hope this helps!
