### ISSUE TITLE
uploadMultiple: true

### ISSUE THREAD

**Issue by cielmik** [ncuesta/dropzonejs-rails#34]
I'm currently having a problem with multiple uploads in one post request. 

this is my current dropzone settings:

var dropzone = new Dropzone (".dropzone", {
		    maxFiles: 10,
		    maxFilesize: 5,
		    paramName: "pictures[]",
		    addRemoveLinks: true,
		    autoProcessQueue: false,
		   uploadMultiple: false,
		   parallelUploads: 10
		  });

$(".submit").click(function (e) {
		   e.preventDefault();
		    e.stopPropagation();
		    dropzone.processQueue();
		    });

My issue is that setting uploadMultiple to true will not let me upload anything(returns nil). 

Setting uploadMultiple: false works, but each file is one post request. e.g. 3 photos is album_id: 1,album_id: 2,album_id: 3. I wanted 3 photos be in one post request so that they will all belong to the same album_id.

Is uploadMultiple:true not working with rails?

**Comment by ncuesta** [comment]
Hi @cielmik, thanks for using this gem.

That should work with Rails.. I'm having a hunch it may be an issue with your controller. Could you please post the relevant portions of your `PicturesController` (or whichever name it has)?

**Comment by cielmik** [comment]
Hi @ncuesta, thank you very much for trying to solve my problem

here is my controller:

```
  def create
    @album = Album.new(album_params)
    respond_to do |format|
      if @album.save
        save_pictures
        format.html { redirect_to root_path, notice: 'Album was successfully created.' }
        format.json { render json: @album }
      else
        flash[:danger] = "Album has not been saved."
        render 'new'
      end
    end
  end

    private
    def save_pictures
      if params[:pictures]
        params[:pictures].each { |image|
          @album.pictures.create(image: image)
        }
      end
    end

my view (slim)
= simple_form_for @album, :html => { :class => 'dropzone', id: "my-dropzone", multipart: true } do |f|
  = f.input :name, class: "form-control"
  .fallback
    = file_field_tag "pictures[]", multiple: true
  = f.button "submit", class: "btn btn-primary item-submit"
```

This is the output I get when trying to save with uploadMultiple: true

 SQL (5.0ms)  INSERT INTO "pictures" ("image", "album_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["image", nil], ["album_id", 44], ["created_at", "2016-03-03 02:04:31.756316"], ["updated_at", "2016-03-03 02:04:31.756316"]]

Thank you very much.

**Comment by cielmik** [comment]
Okay I solved the problem. 
Solution:
Per the documentation:
http://www.dropzonejs.com/#config-paramName 

paramName will be appended with a []

So in this example:
input multiple="multiple" class="file optional" type="file" name="pictures[]" id="album_images" 

Each additional image will append a name = pictures[][0..(NumPicture)].
e.g 3 images
pictures[][0] , pictures[][1], pictures[][2]

My solution is to remove the appended [] in dropzone.js so each additional image will not be appended with []. 
IN the example above what you would want for each image is:
pictures[], pictures[], pictures[]

To remove it, just search for this line in dropzone.js:
return "" + this.options.paramName + (this.options.uploadMultiple ? "[" + n + "]" : "")

and delete  (this.options.uploadMultiple ? "[" + n + "]" : "")

so it will just be:

return "" + this.options.paramName

**Comment by ncuesta** [comment]
Hi @cielmik sorry for the late response.

I don't think you would want to modify Dropzone's source code. Specially for this kind of situations, where the default behavior is pretty close to what you want to achieve.

Maybe you could accept the parameters using something like `params.permit(pictures: [:file])` and then ignoring the indexes in your `each` block, but leaving Dropzone's source code as is..

How does that sound?

Cheers

**Comment by ncuesta** [comment]
Oh, I totally missed the configuration part: You should also drop the trailing `[]` in your `paramName` setting, like this:

    paramName: "pictures",

**Comment by cielmik** [comment]
hi @ncuesta, it's okay and I appreciate your help. 

I'm gonna try your suggestions and report back.

**Comment by cielmik** [comment]
Here is a sample gallery I made if you want to play around with it 

https://github.com/cielmik/dropzone-photoswipe-gallery-rails

This one still has the edited dropzone.js

**Comment by cielmik** [comment]
@ncuesta 
It seems like pictures[0]..pictures[n+1] won't transact to database, it has to be pictures[] without a number inside the brackets for it to work. Is there a way to remove the n inside the brackets without editing dropzone.js?

**Comment by ncuesta** [comment]
Hi @cielmik , you could just use something like

```ruby
params.require(:album).permit(:name, :title, :description, pictures: [])
```

Does that work for you?

**Comment by cielmik** [comment]
@ncuesta I have finally solved it. Thank you.

This is without editing dropzone.js
Here is the answer:

form file get:
`    = file_field_tag "pictures[]", multiple: true`

your js for dropzone

```
     paramName: "pictures",
     uploadMultiple: true
```

Controller:
 ```
 def create
    @album = Album.create(album_params)
    respond_to do |format|
      if @album.save
        save_pictures
        format.html { redirect_to root_path, notice: 'Album was successfully created.' }
        format.json { render json: @album }
      else
        flash[:danger] = "Album has not been saved."
        render 'new'
      end
    end
  end

 private
    def save_pictures
      if params[:pictures]
        params[:pictures].each do |image|
          @album.pictures.create(image: image.pop)
        end
      end
    end
```
file_field_tag doesnt require any permit

the key is here:

```
        params[:pictures].each do |image|
          @album.pictures.create(image: image.pop)
        end
```
 each |image| will give two arrays `[0, file1], [1, file2], [2, file3]`, so image.pop will get the files and pass it on to the server.

**Comment by ncuesta** [comment]
I'm glad you were able to solve it! Cheers.
