### ISSUE TITLE
How to get this working with turbolinks 5?

### ISSUE THREAD

**Issue by gbrl** [ncuesta/dropzonejs-rails#37]
Does anyone know how to get this working with turbolinks? When I reload the page, dropzone loads, but when I navigate using the nav (turbolinks) dropzone isn't loaded.

Thanks!

**Comment by ncuesta** [comment]
Hi @gbrl, you need to initialize your Dropzone elements on the `turbolinks:load` event, as [stated in Turbolinks' README](https://github.com/turbolinks/turbolinks#running-javascript-when-a-page-loads).

Cheers!
