### ISSUE TITLE
Rails SASS dependency

### ISSUE THREAD

**Issue by mlh758** [ncuesta/dropzonejs-rails#42]
There are two scss files included in the project [here](https://github.com/ncuesta/dropzonejs-rails/tree/master/app/assets/stylesheets/dropzone). These require rails-sass in order to be included, which isn't specified in the gemspec.

**Comment by mozi22** [comment]
Hi, did you resolve this ?

**Comment by ncuesta** [comment]
Hi @mlh758! Sorry for the delayed response.

As stated [in sass-rails' README](https://github.com/rails/sass-rails#installing), Rails 3.1+ projects should include the dependency. Am I missing something here?

Thanks!

**Comment by mlh758** [comment]
We must have some internal thing removing that automatically then since we're using 4.2.8. Go ahead and close this!

**Comment by ncuesta** [comment]
Ok, thanks for the quick reply! Ping me if you need a hand.

Cheers!
