### ISSUE TITLE
AWS S3 : Unable to get callback for more than 5 files 

### ISSUE THREAD

**Issue by ParthivPatel-BTC** [ncuesta/dropzonejs-rails#46]
Using rails application, I am trying to upload more than 5 images at a time and the maxFiles is set to 8. I am using `carrierwave` and `dropzonejs-rails` gems to upload files. When I select 5 images and upload, getting success callback but not getting any callback for 6 images after uploading to S3. Have a look at below my dropzone configurations
```js
paramName: 'file',
uploadMultiple: true,
maxFiles: 8,
maxFilesize: 5,
addRemoveLinks: true,
autoProcessQueue: false,
parallelUploads: 8,
acceptedFiles: '.jpeg,.jpg,.png,.gif',
dictMaxFilesExceeded: "Maximum upload limit reached",
url: '/upload_equipment_images',
method: 'post',
dictInvalidFileType: "upload only JPG/PNG/GIF",

**Comment by ncuesta** [comment]
Hi @ParthivPatel-BTC, thanks for getting in touch! Unfortunately, this kind of questions are better off asked at Dropzone's repo. This is just a wrapper around the JS files to ease their inclusion in Rails apps.

Good luck with your problem!

Cheers,
Nahuel

**Comment by NeelTandel-BTC** [comment]
Hello, @ParthivPatel-BTC have you fixed this issue?
