### ISSUE TITLE
Don't know how to build task 'dropzone:check'

### ISSUE THREAD

**Issue by biastoch2** [ncuesta/dropzonejs-rails#48]
Hi,

running rake dropzone:check as noted in the Readme yields to `Don't know how to build task 'dropzone:check'`. I am using the 0.8.2 version of this gem, Rails 5.1 and Ruby 2.3. `rake -T` does not list any other dropzone tasks neither. Dropzone itself works just fine.
Is anybody experience this error too or am I doing just something simple wrong?

Thanks!

**Comment by ncuesta** [comment]
Hi @biastoch2! That task is intended for using when developing (or upgrading) this gem, but *not in the project in which this gem is used*.

Upgrades to the assets (JS & CSS) will be released as new versions of this gem. There's no need for checking for updates from your project.
