### ISSUE TITLE
Setup in Rails 6.0

### ISSUE THREAD

**Issue by kwhandy** [ncuesta/dropzonejs-rails#58]
I've been install this gem into my existing app but when I tried to require it inside my application.js(with webpacker) it doesn't work? What should I do?

**Comment by ncuesta** [comment]
Hi @kwhandy - this gem is intended for using it with Sprockets. If you're running webpacker in your project, I think you'll be better off by using the Dropzone JS lib directly by installing it with `yarn` or `npm`.
